version: "3"

services:
    nginx_server:
        image: nginx
        ports:
            - 8020:80
        volumes:
            - ./settings_resolver:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
    fake_mdm:
        ports:
            - 5000:80
        build: ./fake_mdm

    fake_sudir:
        ports:
            - 8025:80
        build: ./fake_sudir
        volumes:
            - ./fake_sudir_db:/app/website/database

    rabbit_mq:
        ports:
            - 5672:5672
            - 15672:15672
        image: rabbitmq:3-management
        hostname: 'mabbit'
        volumes:
            - ./rabbitmq_data:/var/lib/rabbitmq/mnesia/

    redis:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - ./redis_deg_data:/data

    postgres:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: deg_user
            POSTGRES_PASSWORD: deg_user_password
            POSTGRES_DB: deg_ballot_db
            PGDATA: /postgres_data
        volumes:
            - ./potgres_deg_data:/postgres_data

    pg_adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
